"TMBRTBK":"Trust Me Bro Real Time Based Kernel"
"TMB": "trust me bro"
"JSKBOS":"Jennys Shitty Kernel Based OS(JSKBOS)"
"LITH":"like that"
"ITH":"I think"
"TEST":"test123 please ignore"
"WWHA":"wait what"
"THBA":"thats basicly it"
"YATH":"yeah that"
"FORA":"for some reason"
"WTHTH":"with the"
"AFALL":"after all"
"WWOU":"why would"
"GP":"good point"
"IDL":"I dont like"
"OSMTH":"or something"
"IMEA":"I mean"
"INOSEE":"I dont see" quick warning; the ordering of the words matters here
"WYDI":"why did" for example if you put "why":"y" then "whyd":"why did you"then whyd --> yd rather then into why did you
"WHRUT":"what are you talking about"
"WYNOTL":"why I dont like"
"THISS":"this is"
"HWDO":"how do"
"ITHE":"in the"
"SONE":"someone"
"ICUZ":"its CUZ"
