"lol":"lol"
"wtf":"what the fuck"
"o7":"o.7"
"TTS":"T.T.S"
"rn":"right now"
"ig":"I guess"
"cuz":"because"
"idrk":"I dont really know"
"idk": "I dont know"
"idfk":"I dont fucking know"
"yk":"you know"
"/":" slash "
"hru": "how are you?"
"asf": "as fuck"
"alr":"all right"
"tbf":"to be fair"
"ngl":"not gonna lie"
"imo":"in my opinion"
"imho":"in my honest opinion"
"ofc":"of course"
"smth":"something"
